lbryio/lbrycrd

- .gitignore
- src/miner.cpp
- src/miner.h
- src/rpc/mining.cpp
The original gethashespersec rpc command was implemented in bitcoin core, but was removed in Jan 2015 shortly before they removed the internal miner. Most of the code has been copied verbatim, but there were some structural file changes, as well as api changes, that I've adjusted for. When I ran this, I got 168 KH/s on my macbook.
> Resurrect gethashespersec

- src/chainparams.cpp
The introduction of the new retargeting function caused blocks in regtest mode to take a very long time to generate, which results in the tests taking a very very long time to run. This makes blocks in regtest generate faster.
> make regtest generate blocks faster so that tests run in a reasonable amount of time

- src/main.cpp
- src/nameclaim.cpp
- src/nameclaim.h
- src/test/transaction_tests.cpp
This patch limits name length of claimtrie transactions to 255 bytes at most. 
This is a soft fork, and nodes should upgrade immediately.
> Limits name length of claimtrie transactions to 255 bytes

- src/rpc/mining.cpp
getblocktemplate is supposed to output all required mining infos
> rpc: add claimtrie field in getblocktemplate

- src/chainparams.cpp
- src/test/claimtrie_tests.cpp
This adds a test which checks that someone can't just set claimId to whatever they want when creating a claim update (for example, the claimId of the current winner) and get their claim inserted immediately (or ever).
> Bogus claimid tests

- src/rpc/claimtrie.cpp
getvalueforname now returns total quantity attached to a claim in field "effective amount", including all the supports.
> adding effective amount to rpc command getvalueforname

- src/clientversion.h
This sets client version as release : 
https://github.com/lbryio/lbrycrd/issues/48
will also fix 
https://github.com/lbryio/lbrycrd/pull/43
> Set client version as release

- src/main.cpp
This is a redo of https://github.com/lbryio/lbrycrd/pull/45, containing only the fix and not the test which is contained in https://github.com/lbryio/lbrycrd/pull/52
Fixing below exception that would occurs, when decrementing block and calling function "removeSupportFromMap" to undo a support which has been spent on a txin that is NOT txin[0]
lbrycrdd: claimtrie.cpp:2294: bool CClaimTrieCache::decrementBlock(insertUndoType&, claimQueueRowType&, insertUndoType&, supportQueueRowType&, std::vectorstd::pair<std::basic_string<char, int> >&) const: Assertion `removeSupportFromMap(itSupportUndo->name, itSupportUndo->outPoint, support, false)' failed.
Essentially, the bug caused spent supports to not be undoable. Thus when decrementing a block where a support is spent, the support would still be …
> Fix remove support bug

- src/claimtrie.cpp
- src/claimtrie.h
- src/rpc/claimtrie.cpp
- src/test/claimtriebranching_tests.cpp
Redo of https://github.com/lbryio/lbrycrd/pull/36 (without changes for decimal amounts) 
Add getEffectiveAmountForClaim command to CClaimTrie as per Jimmy's comment for use in rpc command getvalueforname 
Fixes issue https://github.com/lbryio/lbrycrd/issues/33
Add some tests for the new function in claimtriebranching_tests.
> Adding effective amount function to CClaimTrie

- src/rpc/claimtrie.cpp
Increase the maximum amount that a rpc call is allowed to decrement blocks from 20 to 50. This affects how far RPC command getprooforname, used by lbryum, can go back in blocks. 
Calling getproofforname and going back 50 blocks takes about 0.009 seconds (going back 20 blocks takes about 0.007) which should not be too much of a load increase.   
This should decrease cases where we get the error "Block too deep to generate proof" from lbryum when calling its getvalueforname command.
> Change max block decrement amount to 50

- src/rpc/claimtrie.cpp
Presently, to determine a claimId for a winning claim one must first `getvalueforname`, and then separately call `getclaimsfortx`.
> add claimId to return from getvalueforname

- src/rpc/mining.cpp
getblocktemplate command was not returning the correct claimtrie hash updated with the transactions in the block
> Fix getblocktemplate command not returning the correct claimtrie hash

- src/claimtrie.cpp
b2ba3f5
There was a memory leak which would cause a extra ClaimTrie node to be allocated but never deleted. 
This would happen when a new node would be created in the ClaimTrie and CClaimTrieCache.addNodeToCache() was called. 
The only reason the extra ClaimTrie node was created was to serve as a empty node template which would be copied by value over to the actual Node (I guess it looks like a DRY shortcut that was not implemented correctly). This is not necessary, and the fix just creates an empty node when necessary.
a2fa2c0
the was a missing clear() on a cache object in CClaimTrieCache. This should not cause any problem since we don't need to call clear() on map objects that are going to get destroyed anyways but nonetheless should be consistent. 
Was able to reindex with this patch, …
> Fix memory leak

- src/wallet/rpcwallet.cpp
Specify value field in RPC command claimname and updateclaim with hex encoded decimal strings. Also removed some whitespaces at end of line in file rpcwallet.cpp while I was doing this.
https://github.com/lbryio/lbrycrd/issues/101
> RPC commands claimname and updateclaim now take hex encoded "value" argument

- src/lbry.cpp
bnOld was used as a debugging variable in the retargeting algorithm and was never removed. Removed it.
Also clean up white spaces.
> Remove debugging variable bnOld in retarget algorithm

- reproducible_build.sh
In reproducible_build.sh, to build libevent, it would just download from the master branch of libveven'ts github repo without checking out any specific version. 
Download 2.0.22 release instead as specified here: https://github.com/lbryio/lbrycrd/blob/master/depends/packages/libevent.mk
> use specific version of libevent in reproducible builds

- src/Makefile.test.include
- src/main.cpp
- src/main.h
- src/nameclaim.cpp
- src/nameclaim.h
- src/test/claimtriebranching_tests.cpp
- src/test/nameclaim_tests.cpp
- src/test/test_bitcoin.cpp
- src/wallet/wallet.cpp
7f2f918 / reworked to: 1f137fc 
Add new function CalcMinClaimTrieFee to calculate the minimum fee required for claim trie transactions. Works based on MIN_FEE_PER_NAMECLAIM_CHAR , which defines the fee attached per each character of the name in the name claim. Set to 200000 base units or (0.002 LBC) for max fee 0.51 LBC (0.002*255 max length name claim). 
Added test for it in nameclaim_tests.cpp (that we should expand with other tests for nameclaim.cpp) 
8384c04 / reworked to: 12784d4
increase DEFAULT_TRANSACTION_MAXFEE from 0.1 to 1 since we can now get fees over 0.1 LBC
7f2f918 / reworked to: 5c4d8b9
implement CalcMinClaimTrieFee into AcceptToMemoryPool to allow CalcMinClaimTrieFee to take effect when rejecting transactions from the memory pool. Implement CalcMinClaimTrieFee into …
> Add fees to claim trie transactions

- src/test/claimtriebranching_tests.cpp
Noticed that in test fixture best_claim_effective_amount_equals, we called getEffectiveAmountForClaim() but never used its result. This is likely why the error in this PR https://github.com/lbryio/lbrycrd/pull/123 was never caught. 
There is not really any functional difference between the original code and this change. 
Noting that a small minor difference is that the effective amount returned in getInfoForName claim value is calculated on demand and may not necessarily be the correct value. For example upon lbrycrdd restart, the effective amount returned by getInfoForName will be garbage because it hasn't been calculated yet.  This has no impact on these unit tests because we do not test restarts.
> Small fix for best_claim_effective_amount_equals 

- src/pow.cpp
chainparams parameter : fPowAllowMinDifficultyBlocks , which is set to true only on testnet, was designed to allow the difficulty to adjust to the minimum difficulty if a block was not found within 2x target block time. 
This parameter was not working due to the fact that we'd never enter the if statement in line https://github.com/lbryio/lbrycrd/blob/master/src/pow.cpp#L23  since our params.DifficultyAdjustmentInterval() is 1 
This has been fixed and should allow testnet to proceed when a large amount of hashrate drops off the network.
> fix fPowAllowMinDifficultyBlocks to work on the testnet

- src/chainparams.cpp
- src/claimtrie.cpp
- src/claimtrie.h
- src/consensus/params.h
- src/init.cpp
- src/main.cpp
- src/test/claimtriebranching_tests.cpp
**Details of hard fork for all:**
The fork of the mainnet will be on block 400155 (will be around noon EST 7/9/18) 
The fork of the testnet will be on block 280831 (will be around noon EST 5/21/18)
Claims made on and after the target hardfork blocks will expire after 2102400 blocks (approximately 10 years assuming block time 2.5 minutes).
Claims that were made before the hardfork and have not expired will have their expiration extended by the difference between the new expiration time and the previous expiration time (456 days). 
Claims that already expired will remain expired. 
**Details for reviewers**
This is further work off of : https://github.com/lbryio/lbrycrd/pull/110 in order to add the extension of claim expiration to already existing claims ( in #110 claims made before the hard …
> Add capability to extend expiration time of pre fork claims

- src/pow.cpp
We need to make sure that the new fPowAllowMinDifficultyBlocks only affects block 277299 and onwards, otherwise previous blocks that were created without this logic will be invalid because the difficulty calculations for the block will be incorrect.
> fix fPowAllowMinDifficultyBlocks 

- src/rpc/blockchain.cpp
Lbrycrd's maximum target is 0x0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff or in nBits 0x1f00ffff, compared to Bitcoin's maximum nBits 0x1d00ffff
We never adjusted the GetDifficulty() function to reflect this change (29 == 0x1d , 32==0x1f). This change makes it so that the lowest difficulty we can have is 1 , instead of some decimal number. 
I'm not aware of any applications that uses this difficulty readings from RPC commands so its probably ok to change this.   
See https://en.bitcoin.it/wiki/Difficulty for more info.
> normalize difficulty so that 1 == minimum difficulty

- .travis.yml
- README.md
- doc/developer-notes.md
- reproducible_build.sh
- src/.clang-format
Added an option on reproducible_build.sh to run a code formatting check on any commits not on master (by default this option is off). Travis will use this option and build will fail if it finds any lines that needs to be formatted.
For https://github.com/lbryio/lbrycrd/issues/157
> Run code formatting checks on travis

- .travis.yml
After talking with @nikooo777 about our expired GitHub credentials and the desire to include the branch builds, we have changed it to push to our S3 account (available at http://build.lbry.io/lbrycrd/ ). Since we release rarely, it seemed easy enough for me to just copy builds from there to GitHub. As it stands here, there is only one build per branch/tag stored.
> S3 deployment

- CMakeLists.txt
- src/qt/paymentrequestplus.cpp
- src/wallet/crypter.cpp
I was going to wait for the upstream merge, but I don't want to have to explain this problem in my introductory video.
> fixed incompatibility with newer libssl

- src/chainparams.cpp
- src/consensus/params.h
- src/pow.cpp
When we get a delayed block, we thereafter knock the difficulty so low that it takes multiple (up to a 100) blocks to get back up to sufficient difficulty. It doesn't make sense for us to do this as we already adjust difficulty every block.
> fixed blocks coming in too fast on testnet

- doc/REST-interface.md
- src/rest.cpp
- test/functional/interface_rest.py
This is for Flipside crypto. It allows them to use our SSL rest endpoint (rest.lbry.tech) for their query analysis.
> allow rest/block/height.json

- contrib/devtools/generate_json_api_jrgen.py
- contrib/devtools/generate_json_api_v1.py
- contrib/devtools/generated/api_jrgen.json
- contrib/devtools/generated/api_v1.json
- src/Makefile.am
- src/Makefile.test.include
- src/chainparams.cpp
- src/claimtrie.cpp
- src/claimtrie.h
- src/claimtrieforks.cpp
- src/consensus/params.h
- src/dbwrapper.cpp
- src/init.cpp
- src/prefixtrie.cpp
- src/prefixtrie.h
- src/rpc/claimtrie.cpp
- src/rpc/server.cpp
- src/test/claimtriebranching_tests.cpp
- src/test/claimtriecache_tests.cpp
- src/test/dbwrapper_tests.cpp
- src/test/miner_tests.cpp
- src/test/prefixtrie_tests.cpp
- src/test/test_bitcoin.cpp
- src/test/test_bitcoin.h
- src/txdb.h
- src/validation.cpp
- src/wallet/rpcwallet.cpp
- test/functional/feature_help.py
This PR addresses the following issues:
Fixes #106 (Reimplement claimtrie without so many empty nodes, save RAM)
Fixes #108 (Separate data structure and data operations)
Fixes #133 (Trie serialization failure)
Fixes #138 (Rename nCurrentHeight)
Fixes #145 (Rename CClaimTrieCache)
Fixes #158 (Properly delete CClaimTrieNode)
It also includes these enhancements:
1. BLOCK_HASH is no longer needlessly stored in the claimtrie DB. I had a theory that this was masking places that we should have been comparing the claimTrieHash, which theory proved correct.
2. An issue with takeover height computation was detected and (temporarily) worked around.
3. cachedTakeoverHeights was removed; we now use the takeoverHeight field on the nodes in the cache.
4. The getQueue* functions now re-use code.
5. …
> Memory improvements, claimtrie revamp

- README.md
From version 0.16 the use of argument "getinfo" with lbrycrd-cli return the error code -32601; 
as suggested in the resulting output, use instead "-getinfo" in order to get info as the old format.
> Fix lbrycrd-cli command typo

- src/chainparams.cpp
- src/claimtrie.cpp
- src/claimtrie.h
- src/claimtrieforks.cpp
- src/dbwrapper.cpp
- src/dbwrapper.h
- src/init.cpp
- src/leveldb/include/leveldb/env.h
- src/leveldb/table/format.cc
- src/leveldb/util/env_posix.cc
- src/miner.cpp
- src/prefixtrie.cpp
- src/prefixtrie.h
- src/rpc/claimtrie.cpp
- src/serialize.h
- src/streams.h
- src/test/claimtriebranching_tests.cpp
- src/test/claimtriecache_tests.cpp
- src/test/test_bitcoin.cpp
- src/test/test_bitcoin.h
- src/validation.cpp
- src/wallet/db.cpp
- src/wallet/test/claim_rpc_tests.cpp
This change separates out the cliams from the nodes and puts each in separate storage in order to reduce disk writes.
> Drastically reduce repetitive disk writes

- src/Makefile.am
- src/claimtrie.cpp
- src/claimtrie.h
- src/claimtrieforks.cpp
- src/rpc/claimrpchelp.h
- src/rpc/claimtrie.cpp
- src/rpc/client.cpp
- src/test/claimtriebranching_tests.cpp
- src/test/claimtriecache_tests.cpp
- src/validation.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/test/claim_rpc_tests.cpp
A bunch of updated rpc keys can lead to breaking changes in users, note it uses camelCase name notation, it can be changed as well. Notable changes:
nomalized_name -> normalizedName
txid -> txId
nHeight -> height
nValidAtHeight (valid at height) -> validAtHeight
nAmount -> amount
nEffectiveAmount (effective amount) -> effectiveAmount
total names -> totalNames
total claims -> totalClaims
total value -> totalValue
Most values in getclaimsfortx
> [WIP] Unify and extend rpc methods to bid and sequence

- src/claimscriptop.cpp
- src/claimtrie.h
- src/claimtrieforks.cpp
- src/nameclaim.cpp
- src/nameclaim.h
- src/rpc/client.cpp
- src/test/nameclaim_tests.cpp
- src/wallet/rpcwallet.cpp
The nonstandard transactions themselves should be okay in the current code; we just don't want a different hash or trie computation until the fork height.
Fixes #272
> initial commit of metadata on supports

- src/rpc/client.cpp
- src/script/sign.cpp
- src/wallet/rpcwallet.cpp
The basic process:
```
1. cli addtimelockedaddress <block height or time> <receiver address 1>
2. cli sendtoadderss <address result from step 1> <amount>
3. cli getrawtransaction <txid from step 2> true
4. cli createrawtransaction '''[ {"txid":"<txid from step 2>", "vout":<n from step 3> } ]''' '''[ { "<receiver address 2>":<amount minus fee> } ]''' <block height from step 1>
On receiver machine:
5. importaddress <redeemScript from step 1> "" false true
6. cli signrawtransactionwithwallet <bytes from step 4>
7. cli sendrawtransaction <bytes from 6>
If you set the block height too low on 4 the signing will fail. If you try to send the transaction before the proper time the send will fail.
```
> added helper method for timelock, enabled signing of timelock

- autogen.sh
- contrib/macdeploy/detached-sig-apply.sh
- contrib/macdeploy/detached-sig-create.sh
- contrib/windeploy/detached-sig-create.sh
- packaging/build_darwin_64bit.sh
- packaging/build_linux_64bit.sh
- packaging/build_windows_32bit.sh
- packaging/build_windows_64bit.sh
- src/univalue/autogen.sh
- test/lint/commit-script-check.sh
Hello,
Backticks are discouraged for any new scripts, since they complicate nesting, quoting, and escaping, besides being graphically less explicit. 
Thanks.
Ref:
http://mywiki.wooledge.org/BashFAQ/082. 
https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_06_03
> Fix 'Use $(...) notation instead of legacy backticked `...`.' issue

- src/init.cpp
- src/logging.cpp
- src/logging.h
As discussed in #211, this PR introduces the automatic moving of and existing log file to an `.old` file. This means logs are preserved for the last 2 executions, and also implies the -shrinkdebugfile is no longer useful, and thus removed.
Please tell me if there are any improvements to be made.
> Implement basic log rotation (closes #211)
