lbryio/lbrycrd

.travis.yml, depends/Makefile, packaging/build_windows.sh, packaging/remove_consensus.patch, share/setup.nsi.in, src/Makefile.am
Compiles lbrycrdd using mingw to produce a windows executable
=> add windows build to travis

src/chainparams.cpp, src/claimtrie.cpp, src/claimtrie.h, src/rpc/claimtrie.cpp, src/wallet/rpcwallet.cpp
this starts to switch rpc functions over to using claimids. i have not yet tested to see if it actually works.
=> Claimid rpc updates

src/test/claimtrie_tests.cpp, src/test/lbry_tests.cpp
Adding two tests:
1) make sure blocks with bogus claimtrie hash are invalid
2) check pow algorithm hashes
=> New basic tests

src/primitives/transaction.h, src/test/transaction_tests.cpp
for https://github.com/lbryio/lbrycrd/issues/25
undos https://github.com/lbryio/lbrycrd/commit/a6984a9d72f9231ff850050b0193342a1ce8c043
=> Re-enable dust threshold checks

src/nameclaim.cpp, src/nameclaim.h
This adds claimtrie script generation functions to nameclaim.h 
Required for https://github.com/lbryio/lbrycrd/pull/39 and https://github.com/lbryio/lbrycrd/pull/45
=> Adding claimtrie script generation functions

src/Makefile.test.include, src/test/claimtriebranching_tests.cpp
This is a redo of https://github.com/lbryio/lbrycrd/pull/39, containing the new claimtrie branching test, and the test for the remove support bug. 
In the future, will need to merge claimmtrie_tests into claimtriebranching_tests to make a single test for claimtries.
=> Claimtrie branching tests with test for remove suppport bug

src/claimtrie.cpp, src/test/claimtriebranching_tests.cpp
Fixes : https://github.com/lbryio/lbrycrd/issues/77
=> Fix lbrycrd crashing 

src/test/claimtriebranching_tests.cpp
Added a test claimtriebranching_tests to check if updates alter the expiration time as expected.
=> Added expiration test 

src/claimtrie.cpp, src/test/claimtriebranching_tests.cpp
Fixed a missing block after the if statement and added some more tests, they fail without the fix.
=> Test and fix CClaimTrie::getEffectiveAmountForClaim

reproducible_build.sh
=> Fix openssl build on 32 bit Linux

README.md, src/util.cpp
Added a data directory section to README, 
Also fixed comments that were listing bitcoin directories in util.cpp
=> Add a data directory section to README

README.md
For https://github.com/lbryio/lbrycrd/issues/154
=> add note about c++/gcc version, adjust formatting in README

reproducible_build.sh
Testing python install, not expected to work just yet
=> Resolves OS X Travis build issue

reproducible_build.sh
I think this should fix:
https://travis-ci.org/lbryio/lbrycrd/jobs/401577592
=> fix clang_format_diff in reproducibel_build.sh

reproducible_build.sh, src/test/claimtrie_tests.cpp, src/test/claimtriebranching_tests.cpp
First, re-enable OS X tests to see what's going wrong ...
=> Fix OS X unit tests

.gitignore, CMakeLists.txt
(not to be used for a full compile of the project)
=> Support for CLion Intellisense

src/wallet/rpcwallet.cpp
=> Do not create transactions with incorrect claims

src/main.cpp
=> Specify non standard tx errors

src/rpc/claimtrie.cpp
=> Remove unnecessary copies

src/claimtrie.cpp, src/claimtrie.h, src/main.cpp, src/main.h, src/rpc/claimtrie.cpp, src/test/claimtriebranching_tests.cpp, src/test/claimtriecache_tests.cpp
I'm marking this as WIP as I'm unsure on the approach and looking for feedback. You'll notice that `getclaimsforname` is done differently (more robustly) than the others. The others could be done like that one but not vice-versa, but I'm less sure on the consequences of that approach and the completeness of what's there.
=> added blockhash input to claimtrie RPC methods plus tests

src/rpc/claimtrie.cpp
=> Return the value field to getclaimsforname rpc method

src/rpc/claimtrie.cpp
=> Return correct field "supports without claims"

src/script/ismine.cpp, src/wallet/wallet.cpp
Added bonus: Brings sync time back to under an hour.
=> Fix a bug that treats all claims as our own wallet txs.

src/rpc/mining.cpp, src/test/claimtriebranching_tests.cpp
I also included a test to ensure that we don't forget it next time, and skipped some checks when we're in regtest to allow the test to run.
=> added claimtrie field back to getblocktemplate

src/miner.cpp
fixed ancestors not all in claim trie on packageFees condition
=> repair bad hash computation in miner

src/rpc/mining.cpp
support coinbasetxn capability in getblocktemplate
=> allow local (non-pool) mining with ccminer and sgminer

src/chainparams.cpp, src/claimscriptop.cpp, src/claimscriptop.h, src/claimtrie.cpp, src/claimtrie.h, src/claimtrieforks.cpp, src/init.cpp, src/miner.cpp, src/miner.h, src/test/claimtriebranching_tests.cpp, src/validation.cpp
=> Fix expiration fork usage

.gitignore, src/claimtrie.cpp, src/claimtrie.h, src/claimtrieforks.cpp, src/test/claimtriebranching_tests.cpp, src/test/claimtriecache_tests.cpp
=> Code refactor

.travis.yml, src/chainparams.cpp, src/claimtrie.cpp, src/claimtrie.h, src/claimtrieforks.cpp, src/consensus/params.h, src/init.cpp, src/miner.cpp, src/prefixtrie.cpp, src/prefixtrie.h, src/rpc/claimtrie.cpp, src/test/claimtriebranching_tests.cpp, src/test/claimtriecache_tests.cpp, src/test/test_bitcoin.cpp, src/validation.cpp
=> Implement binary tree hash algorithm

src/chainparams.cpp, src/chainparamsbase.cpp, src/qt/networkstyle.cpp, src/qt/paymentserver.cpp, src/rpc/mining.cpp, src/test/data/key_io_valid.json, src/test/util_tests.cpp
=> Match network id to regtest

src/rpc/claimrpchelp.h, src/wallet/rpcwallet.cpp
=> Show claimtrie help in cli rpc

src/claimtrie.cpp, src/claimtrie.h, src/claimtrieforks.cpp, src/init.cpp, src/lbry.cpp, src/lbry.h, src/miner.cpp, src/prefixtrie.cpp, src/prefixtrie.h, src/rpc/claimtrie.cpp, src/test/claimtriebranching_tests.cpp, src/test/claimtriecache_tests.cpp, src/test/claimtrienormalization_tests.cpp, src/test/test_bitcoin.cpp, src/validation.cpp
match previous serialization
added check for RC's data
=> Use memory mapped file for claim data allocations

README.md
Added the MIT license badge that redirects to the license page
=> MIT License badge

README.md
What kind of change does this PR introduce?
Having a _detailed_ table of contents eases the pain of having to search for information in the given file, and gives the user some helpful jump-links to different parts of the documentation.
- Added and Removed whitespaces/blank-lines wherever necessary
- Removed trailing colon mark in headings to comply with best markdown practices
=> Docs: Updated README.md files with TOC and best practices in Markdown

src/claimtrie/sqlite.h, src/claimtrie/sqlite/hdr/sqlite_modern_cpp/type_wrapper.h, src/txdb.h
=> Allow sqlite to copy only temporaries

src/wallet/test/claim_rpc_tests.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp, src/wallet/walletdb.h
=> Fix wallet races and crashes

src/index/blockfilterindex.cpp, src/index/blockfilterindex.h
and made it work right.
Fixes #383
=> keep the block filter entirely in sqlite

src/claimtrie/forks.cpp, src/claimtrie/forks.h, src/claimtrie/trie.cpp, src/claimtrie/trie.h, src/txdb.h, src/validation.cpp
=> Merkle improve

src/chainparams.cpp
add two DNS seeds that are running https://github.com/lbryio/seeder
=> add a couple dns seeds
